services:
  crdb:
    image: cockroachdb/cockroach
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    environment:
        - COCKROACH_DATABASE=database
        - COCKROACH_USER=user1
        - COCKROACH_PASSWORD=password
    volumes:
      - "./data/cockroach-data/crdb:/cockroach/cockroach-data"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: