name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      COCKROACH_USER: dbuser
      COCKROACH_PASSWORD: dbpassword
      COCKROACH_DATABASE: database
      DB_PORT: 26257
      DB_HOST: localhost
      BROKER_URL: nats://localhost:4222
      CACHE_URL: memcached:11211

    services:
      cockrocach:
        image: cockroachdb/cockroach
        ports:
          - "26257:26257"
          - "8080:8080"
        command: start-single-node --insecure
        environment:
          - COCKROACH_DATABASE=database
          - COCKROACH_USER=user1
          - COCKROACH_PASSWORD=password

      rabbit:
        image: rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Install Goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run database migrations
        run: |
          goose -dir /migrations postgres "host=${DB_HOST} user=${COCKROACH_USER} password=${COCKROACH_PASSWORD} dbname=${COCKROACH_DATABASE}" up

      - name: Run tests
        run: go test -v ./internal/notifier/... -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}